"""The whole pipeline, on synthetic data with a known answer.

Every other test checks a layer. This one checks that the layers compose: that
a person with a perfectly regular schedule gets an estimate near the right
place, that the system degrades honestly instead of confidently, and that a
run never leaves the database in a state the next run cannot use.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from zoneinfo import ZoneInfo

import numpy as np
import pytest
from sqlalchemy import func, select

from circa.db.models import (
    HeartRateMinute,
    PhaseEstimate,
    SleepSession,
    StepMinute,
)
from circa.settings_store import Chronotype, RuntimeSettings

TZ = ZoneInfo("America/Chicago")
NOW = datetime(2026, 9, 10, 14, 0, tzinfo=UTC)  # 09:00 local


def _seed_person(
    db,
    nights: int,
    sleep_onset_local: float = 23.5,
    sleep_hours: float = 8.0,
    hr_acrophase_local: float = 16.0,
    jitter_minutes: float = 12.0,
    seed: int = 0,
    gap_days: tuple[int, ...] = (),
):
    """A synthetic person with a stable schedule and a matching HR rhythm."""
    rng = np.random.default_rng(seed)
    offset = -5 * 3600

    with db() as s:
        for d in range(nights, 0, -1):
            if d in gap_days:
                continue
            day = (NOW - timedelta(days=d)).astimezone(TZ).replace(
                hour=0, minute=0, second=0, microsecond=0
            )
            jitter = timedelta(minutes=float(rng.normal(0, jitter_minutes)))
            start = day + timedelta(hours=sleep_onset_local) + jitter
            end = start + timedelta(hours=sleep_hours)
            s.add(SleepSession(
                external_id=f"sleep/{d}",
                start_ts=start.astimezone(UTC), end_ts=end.astimezone(UTC),
                tz_name="America/Chicago", utc_offset_seconds=offset,
                sleep_date=end.date(), session_type="STAGES", is_main_sleep=True,
                tst_minutes=sleep_hours * 60 * 0.92,
                time_in_bed_minutes=sleep_hours * 60,
                midpoint_ts=(start + (end - start) / 2).astimezone(UTC),
                efficiency=0.92, wake_forced=False, excluded=False,
            ))

            # Heart rate: a 24 h cosine peaking at hr_acrophase_local, damped
            # during sleep, plus activity-driven steps in the waking hours.
            for minute in range(0, 24 * 60, 5):
                ts = (day + timedelta(minutes=minute)).astimezone(UTC)
                local_h = minute / 60.0
                asleep = start <= day + timedelta(minutes=minute) < end
                circ = 8.0 * np.cos(2 * np.pi * (local_h - hr_acrophase_local) / 24.0)
                bpm = 62 + circ - (10 if asleep else 0) + rng.normal(0, 2.5)
                s.add(HeartRateMinute(
                    ts=ts, bpm_median=float(bpm), bpm_min=int(bpm - 3),
                    bpm_max=int(bpm + 3), n_samples=12,
                    active_fraction=0.0 if asleep else 0.2,
                ))
                if not asleep and 8 <= local_h < 22:
                    s.add(StepMinute(
                        ts=ts,
                        steps=int(max(0, rng.normal(45, 30)) * (2.0 if 9 <= local_h < 11 else 1.0)),
                    ))


# The filter's cost is dominated by light histories, so these are turned down
# for speed. The code paths under test are identical; only the sample size of
# the ensemble changes.
FAST = {"n_particles": 400, "n_light_samples": 4}


def _fast(**kwargs) -> RuntimeSettings:
    return RuntimeSettings(**{**FAST, **kwargs})


def _estimate(db, settings=None, seed=7):
    from circa.phase import engine

    with db() as s:
        return engine.estimate(s, as_of=NOW, settings=settings or _fast(), seed=seed)


# --- accuracy ---------------------------------------------------------------


def test_a_regular_sleeper_gets_an_estimate_near_the_expected_dlmo(db):
    """Sleep onset ~23:30 with a night-owl prior implies DLMO in the evening.

    Not a validation of the science - the synthetic data is generated by a
    different model than the one being fitted. It is a guard against the whole
    stack producing something absurd, like a melatonin onset at breakfast.
    """
    _seed_person(db, nights=21)
    result = _estimate(db)
    assert result is not None

    local = result.posterior.dlmo_hours
    # DLMO must land in the evening block, well away from the middle of the day.
    assert 18.0 <= local <= 24.0 or 0.0 <= local <= 1.0, f"DLMO at {local:.1f}h local"

    # And CBTmin must sit inside the sleep episode it describes.
    cbt = result.posterior.cbtmin_hours
    assert 1.0 <= cbt <= 8.0, f"CBTmin at {cbt:.1f}h local, outside the night"


def test_estimate_is_deterministic_for_identical_data(db):
    """Unseeded stochastic filtering rewrote the calendar on every poll."""
    _seed_person(db, nights=14)
    a = _estimate(db, seed=None)
    b = _estimate(db, seed=None)
    assert a.dlmo_ts == b.dlmo_ts
    assert a.confidence.q == b.confidence.q


def test_more_nights_do_not_make_the_estimate_less_certain(db):
    """Confidence must be monotone in evidence, all else equal."""
    _seed_person(db, nights=4)
    few = _estimate(db)
    with db() as s:
        s.query(SleepSession).delete()
        s.query(HeartRateMinute).delete()
        s.query(StepMinute).delete()
    _seed_person(db, nights=21)
    many = _estimate(db)
    assert many.confidence.n_nights > few.confidence.n_nights
    assert many.posterior.sd_minutes <= few.posterior.sd_minutes * 1.15


# --- honesty ----------------------------------------------------------------


def test_an_erratic_sleeper_is_reported_as_less_certain(db):
    _seed_person(db, nights=21, jitter_minutes=10, seed=1)
    steady = _estimate(db)
    with db() as s:
        s.query(SleepSession).delete()
        s.query(HeartRateMinute).delete()
        s.query(StepMinute).delete()
    _seed_person(db, nights=21, jitter_minutes=180, seed=1)
    erratic = _estimate(db)
    assert erratic.confidence.q < steady.confidence.q, (
        f"erratic q={erratic.confidence.q} not below steady q={steady.confidence.q}"
    )


def test_cold_start_never_claims_a_high_tier(db):
    _seed_person(db, nights=2)
    result = _estimate(db)
    assert result.confidence.tier == 0
    assert result.confidence.is_low


def test_a_multi_day_gap_does_not_crash_or_inflate_confidence(db):
    _seed_person(db, nights=21, gap_days=tuple(range(5, 15)))
    result = _estimate(db)
    assert result is not None
    assert np.isfinite(result.posterior.sd_minutes)
    assert result.confidence.q <= 1.0


def test_no_data_at_all_returns_none_rather_than_guessing(db):
    assert _estimate(db) is None


# --- the full run -----------------------------------------------------------


def test_full_pipeline_produces_coherent_blocks(db):
    from circa.gcal.blocks import WAKE_REQUIRED_KINDS
    from circa.pipeline import run

    _seed_person(db, nights=21)
    with db() as s:
        report = run(s, as_of=NOW, push_calendar=False, settings=_fast(), seed=7)

    assert not report.errors, report.errors
    assert report.phase is not None
    assert report.blocks, "a mature-looking dataset produced no blocks at all"

    for b in report.blocks:
        assert b.end > b.start, f"{b.kind} ends before it starts"
        assert (b.end - b.start) < timedelta(hours=26), f"{b.kind} spans {b.end - b.start}"
        assert b.title and b.key

    # Waking advice must not land inside the predicted sleep window.
    nights = [b for b in report.blocks if b.kind == "sleep_window"]
    for b in report.blocks:
        if b.kind not in WAKE_REQUIRED_KINDS:
            continue
        for night in nights:
            overlap = min(b.end, night.end) - max(b.start, night.start)
            assert overlap <= timedelta(0), (
                f"{b.kind} overlaps the biological night by {overlap}"
            )


def test_pipeline_is_rerunnable_and_idempotent(db):
    from circa.pipeline import run

    _seed_person(db, nights=21)
    with db() as s:
        first = run(s, as_of=NOW, push_calendar=False, settings=_fast(), seed=7)
    with db() as s:
        second = run(s, as_of=NOW, push_calendar=False, settings=_fast(), seed=7)

    assert not second.errors
    assert [b.key for b in first.blocks] == [b.key for b in second.blocks]
    assert [b.start for b in first.blocks] == [b.start for b in second.blocks]

    with db() as s:
        rows = s.scalar(select(func.count()).select_from(PhaseEstimate))
    assert rows == 1, "a second identical run created a second estimate row"


@pytest.mark.parametrize("chronotype", list(Chronotype))
def test_every_chronotype_runs_end_to_end(db, chronotype):
    from circa.pipeline import run

    _seed_person(db, nights=21)
    with db() as s:
        report = run(s, as_of=NOW, push_calendar=False,
                     settings=_fast(chronotype=chronotype), seed=7)
    assert not report.errors, report.errors
    assert report.phase is not None


def test_paused_setting_writes_nothing(db):
    from circa.pipeline import run

    _seed_person(db, nights=21)
    with db() as s:
        report = run(s, as_of=NOW, push_calendar=False,
                     settings=_fast(paused=True), seed=7)
    assert report.blocks == []
